

<!-- Start of Search Page Mastertag Code: -->
			<div class="zx_<?php echo Mage::getStoreConfig('zanox/general/master_search'); ?> zx_mediaslot">
				<script type="text/javascript">
                    var url = window.location.search.substring(1);
					var zx_search_query = url.split("q=")[1];
                    window._zx = window._zx || [];
					window._zx.push({"id":"<?php echo Mage::getStoreConfig('zanox/general/master_search'); ?>"});
					(function(d) {
						var s = d.createElement("script"); s.async = true;
						s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//static.zanox.com/scripts/zanox.js";
						var a = d.getElementsByTagName("script")[0]; a.parentNode.insertBefore(s, a);
					}(document));
				</script>
			</div>
<!-- End of Search Page Mastertag Code -->
