
<?php
$_productinfo = Mage::registry('current_product');

$cleanDescription = strip_tags( $_productinfo->getDescription() ); //Remove HTML Tags
$cleanDescription = trim( $cleanDescription );

?>
<!-- Start of Product Page Mastertag Code: -->
			<div class="zx_<?php echo Mage::getStoreConfig('zanox/general/master_product'); ?> zx_mediaslot">
				<script type="text/javascript">
                    var zx_identifier = "<?php echo $_productinfo->getId(); ?>";
                    var zx_fn = "<?php echo $_productinfo->getName(); ?>";
                    var zx_description = "<?php echo htmlspecialchars($cleanDescription); ?>";
                    var zx_category = jQuery('body').attr("class").split("category-")[1];
                    var zx_brand = "<?php echo $_productinfo->getManufacturer(); ?>";
                    var zx_price = "<?php echo $_productinfo->getFinalPrice(); ?>€";
                    var zx_amount = "<?php echo $_productinfo->getFinalPrice(); ?>";
                    var zx_currency = "EUR";
                    var zx_url = "<?php echo $_productinfo->getUrl(); ?>";
                    var zx_photo = "<?php echo $_productinfo->getImageUrl(); ?>";
                    var zx_language = "de"
                    window._zx = window._zx || [];
					window._zx.push({"id":"<?php echo Mage::getStoreConfig('zanox/general/master_product'); ?>"});
					(function(d) {
						var s = d.createElement("script"); s.async = true;
						s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//static.zanox.com/scripts/zanox.js";
						var a = d.getElementsByTagName("script")[0]; a.parentNode.insertBefore(s, a);
					}(document));
				</script>
			</div>
<!-- End of Product Page Mastertag Code -->
